# Listening ports
listening-port=3478
tls-listening-port=5349

# Listening IP
listening-ip=0.0.0.0

# Docker-kontin pysyvä relay-osoite -> Windows-hostin julkinen osoite
external-ip=91.157.161.57/172.18.0.10
relay-ip=172.18.0.10

# Relay ports
min-port=10000
max-port=10200

# Realm
realm=videortc.local

# Static user credentials
user=videouser:videopass

# Security
fingerprint
lt-cred-mech

# CLI
no-cli

# Performance
max-bps=1000000
bps-capacity=0

# Allow UDP relay
no-tcp-relay
